-- Create Wallets table
CREATE TABLE IF NOT EXISTS Wallets (
    Id UUID PRIMARY KEY,
    UserId UUID NOT NULL UNIQUE REFERENCES Users(Id) ON DELETE CASCADE,
    Balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
    Currency VARCHAR(3) NOT NULL DEFAULT 'NPR',
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

